spring:
  profiles:
    active: mysql


springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: /api
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /**
    -
---
spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile: h2
  thymeleaf:
    cache: false

