name: Deploy to EC2

on:
  push:
    branches:
      - deploy-ec2

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ../..
    steps:
      - name: deploy
        run: |
          chmod +x ./deploy.sh
          sudo ./deploy.sh

